#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.4"
personality = "pragmatic"
[projects."/Users/kosnu/dev/github.com/kosnu/aibox"]
trust_level = "trusted"

[projects."/Users/kosnu/dev/github.com/kosnu/savings"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[mcp_servers.openaideveloperdocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=flpswdqbgrwnkjtokzfr"

[tui]
notifications = ["agent-turn-complete", "approval-requested"]
notification_method = "auto"

[features]
rmcp_client = true
